#!bash

REPORT_HOME=$HOME/ReportesNetsuite
REPORT_HOME_JAVA=$REPORT_HOME/java/zulu17/bin
REPORT_HOME_REPORTE_ARCHIVOS=$REPORT_HOME/ReporteArchivos

$REPORT_HOME_JAVA/java -jar $REPORT_HOME_REPORTE_ARCHIVOS/ReporteArticulos-1.0.jar
